= Barcode4J with maven (fork of SourceForge original)

image:https://github.com/metanorma/barcode4j/workflows/ubuntu/badge.svg["Build Status", link="https://github.com/metanorma/barcode4j/actions?workflow=ubuntu"]
image:https://github.com/metanorma/barcode4j/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/barcode4j/actions?workflow=macos"]

== Description

Barcode4J is a flexible generator for barcodes written in Java.

For instructions on how to get started please read the documentation on the
website or the one included in the binary distribution.

_Original website_: http://barcode4j.sourceforge.net


== Installing Build Tools

You will need the `maven` build tool and `make`.

* https://www.baeldung.com/install-maven-on-windows-linux-mac[How to install Maven on Windows, Linux, Mac]



== Building the package

[source,sh]
----
make all
----


== Releasing a new version

Update version in `pom.xml`, e.g.:

[source,xml]
----
<groupId>net.sf.barcode4j</groupId>
<artifactId>barcode4j</artifactId>
<packaging>jar</packaging>
<name>Barcode4J</name>
<version>2.2-SNAPSHOT</version>
----

Build the package using instructions above, the package will be created at:
`target/barcode4j-{version}.jar`

Tag the same version in Git:

[source,xml]
----
git tag v2.2
git push origin v2.2
----

Then the corresponding GitHub release will be automatically created at:
https://github.com/metanorma/barcode4j/releases

And downloadable at:
`https://github.com/metanorma/barcode4j/releases/download/v{version}/barcode4j-{version}-SNAPSHOT.jar`


== Testing

The testing environment utilizes these tools:

* `make`


Running the tests:

[source,sh]
----
make test
----


== Copyright

The original Barcode4J is licensed under the the Apache License, Version 2.0.
The license text can be found under legal/barcode4j.LICENSE.txt.

Further modifications are copyright Ribose Inc.
